#ifndef _HAP_H_
#define _HAP_H_

#ifdef __cplusplus
extern "C" {
#endif

enum hap_accessory_category {
    HAP_ACCESSORY_CATEGORY_OTHER = 1,
    HAP_ACCESSORY_CATEGORY_BRIDGE,
    HAP_ACCESSORY_CATEGORY_FAN,
    HAP_ACCESSORY_CATEGORY_GARAGE,
    HAP_ACCESSORY_CATEGORY_LIGHTBULB,
    HAP_ACCESSORY_CATEGORY_DOOR_LOCK,
    HAP_ACCESSORY_CATEGORY_OUTLET,
    HAP_ACCESSORY_CATEGORY_SWITCH,
    HAP_ACCESSORY_CATEGORY_THERMOSTAT,
    HAP_ACCESSORY_CATEGORY_SENSOR,
    HAP_ACCESSORY_CATEGORY_SECURITY_SYSTEM,
    HAP_ACCESSORY_CATEGORY_DOOR,
    HAP_ACCESSORY_CATEGORY_WINDOW,
    HAP_ACCESSORY_CATEGORY_WINDOW_COVERING,
    HAP_ACCESSORY_CATEGORY_PROGRAMMABLE_SWITCH,
    HAP_ACCESSORY_CATEGORY_RANGE_EXTENDER,
    HAP_ACCESSORY_CATEGORY_IP_CAMERA,
    HAP_ACCESSORY_CATEGORY_VIDEO_DOOR_BEEL,
    HAP_ACCESSORY_CATEGORY_AIR_PURIFIER,
};

#ifdef __cplusplus
}
#endif

#endif //#ifndef _HAP_H_
